language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- docker
install:
- pip install keyring==21.4.0
- pip install -r requirements.txt
script:
- pycodestyle TestingLibrarySelectorsPlugin
- pylint -E --enable=invalid-name,unused-import,useless-object-inheritance TestingLibrarySelectorsPlugin
- coverage run --branch --source TestingLibrarySelectorsPlugin/ -m unittest discover -s unit_tests/
- coverage report -m
- docker build . -t atest
- docker run --rm atest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: GuttreNtugt2DT+3fFpct/m1d/L0JRuyV9FtExba03L4EqvPcBC9OXRzC4MSdXWWuQc0e9WeKdR0Jucylk49oagnlbGHwiQy4XA0vIC+MgK6hw2eeHcF5IRCqVDt98dD7y1bFtyOwktDOeZFhCEjmM19L8hXdQa8ZEWg4JJXx4UAcwXjekyg8HPHVXVDDc0oIZroKYZnykOKB1OM2bRhgvQEt7Dvlm4uQtX1W6cUJRvoIl+zsH6AGjrxwXiWyZMSytPs8uSrhthfJuxsgwNsKesJEu8A/Fcaum77mnq6kvPnvSY2hE4H40SEpdW8lEH197lQZf45loa9bjpYPlsML4UdABX+r1QcB38i+lg9fkZVVmT87hHRVE0fWWowPCmeb8CMar6j4/7Ut7eIVJsXCHGxyj/nNTHnn8nFsrbc0b7rMTd1K2p331zXX57pY64M1GLgnb1K6V/VURBZpBiR2shyftRjvFWTWZZeoXqcKWZaY7wDpqcaF2OuBJUdDmAAy4eoMGgt4xSxTP/h1te+VEJzSDDA0fXJhZGyxkN3P9lmL2JW82QUvPpgl8uMbmkcXdUDIk+e3WnugRalACG455/xeoV90ylrlz67G6T90VCSth6KId+2ANauDM5oSEmXkS2HHHDINrXIVnWXvjsFcvegPd6yofPkGg33dRFSXTY=
  on:
    tags: true
    python: 3.7
