name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run static analysis and unittests
      run: |
        pycodestyle TestingLibrarySelectorsPlugin
        pylint -E --enable=invalid-name,unused-import,useless-object-inheritance TestingLibrarySelectorsPlugin
        coverage run --branch --source TestingLibrarySelectorsPlugin/ -m unittest discover -s unit_tests/
        coverage report -m
        docker build . -t atest
        docker run --rm atest
